CREATE DATABASE TIRTH_MODI
USE TIRTH_MODI
CREATE TABLE IF NOT EXISTS TABLE_TIRTH(
Dress_ID VARCHAR(30) NOT NULL,	
Style VARCHAR(30) NOT NULL,	
Price VARCHAR(50) NOT NULL,	
Rating INT(30) NOT NULL,	
Size VARCHAR(30) NOT NULL,	
Season VARCHAR(30) NOT NULL,	
NeckLine VARCHAR(30) NOT NULL,	
SleeveLength VARCHAR(30) NOT NULL,	
waiseline VARCHAR(30) NOT NULL,	
Material VARCHAR(30) NOT NULL,	
FabricType VARCHAR(30) NOT NULL,	
Decoration VARCHAR(30) NOT NULL,	
PatternType VARCHAR(30) NOT NULL,	
Recommendation INT(30) NOT NULL
);
SET SESSION sql_mode = ''
SELECT * FROM TABLE_TIRTH;
LOAD DATA INFILE
'E:/AttributeDataSet.csv'
INTO TABLE TABLE_TIRTH
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
SELECT * FROM TABLE_TIRTH;