CREATE DATABASE SQL_JOIN

USE SQL_JOIN;

CREATE TABLE IF NOT EXISTS CUSTOMERS(
	CUSTOMER_ID INT(30), 
	FIRST_NAME VARCHAR(30) 
);
CREATE TABLE IF NOT EXISTS ORDERS(
	ORDER_ID VARCHAR(30), 
	AMOUNT INT(30),
    CUSTOMER_ID INT(30)
);
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME) 
VALUES (1, 'JOHN'),(2, 'ROBERT'),(3, 'DEVID'),(4, 'JOHN'),(5, 'BETTY'); 

INSERT INTO ORDERS (ORDER_ID, AMOUNT,CUSTOMER_ID) 
VALUES (1,200,10),(2,500,3),(3,300,6),(4,800,5),(5,150,8); 

#INNER JOIN
SELECT CUSTOMERS.CUSTOMER_ID,CUSTOMERS.FIRST_NAME,ORDERS.ORDER_ID FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

SELECT CUSTOMERS.CUSTOMER_ID,CUSTOMERS.FIRST_NAME,ORDERS.AMOUNT FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

ALTER TABLE ORDERS
DROP COLUMN CUSTOMER_ID

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
ADD COLUMN CUSTOMER_ID INT(30);

INSERT INTO ORDERS (ORDER_ID, AMOUNT,CUSTOMER_ID) 
VALUES (1,200,10),(2,500,3),(3,300,6),(4,800,5),(5,150,8);

SELECT * FROM ORDERS;

SELECT CUSTOMERS.CUSTOMER_ID,CUSTOMERS.FIRST_NAME,ORDERS.AMOUNT FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

#LEFT JOIN
SELECT CUSTOMERS.CUSTOMER_ID,CUSTOMERS.FIRST_NAME,ORDERS.AMOUNT FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;


