CREATE DATABASE TIRHT;
USE TIRTH;
CREATE TABLE IF NOT EXISTS TIRTH123(
ID INT(10),
FIRST_NAME VARCHAR(30),
EMAIL_ID VARCHAR(30),
ADDRESS VARCHAR(30),
SALARY INT CHECK(SALARY < 10000)
);
USE TIRTH;
CREATE TABLE IF NOT EXISTS TEST8(
TEST_ID INT NOT NULL AUTO_INCREMENT,
TEST_NAME VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
TEST_MAILID VARCHAR(30) UNIQUE NOT NULL,
TEST_ADRESS VARCHAR(30) CHECK (TEST_ADRESS = 'BENGALORE') NOT NULL,
TEST_SALARY INT CHECK(TEST_SALARY > 10000) NOT NULL,
PRIMARY KEY (TEST_ID));
SELECT * FROM TEST8;
INSERT INTO TEST8 (TEST_ID, TEST_NAME, TEST_MAILID, TEST_ADRESS, TEST_SALARY) 
VALUES (100, 'TIRTH', 'TIRTHMODI@GMAIL.COM', 'BENGALORE', 50000); 
SELECT * FROM TEST8;





