SHOW DATABASES;
CREATE TABLE MYTABLE(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL DEFAULT 'NO EMAIL PROVIDED',
AMOUNT INT,
PRIMARY KEY (ID)
);
INSERT INTO MYTABLE(NAME, AMOUNT)
VALUES('TIRTH',30
);
INSERT INTO MYTABLE(NAME, EMAIL, AMOUNT)
VALUES('TIRTH','TIRTHMODI9@GMAIL.COM',35),
('DINESH','DINESHGOHIL@GMAIL.COM',40),
('PRAKASH','PRAKASHPARMAR@GMAIL.COM',45),
('PRADEEP','PRADEEPSONI@GMAIL.COM',55);
SELECT NAME FROM MYTABLE;
SELECT EMAIL FROM MYTABLE;
SELECT AMOUNT FROM MYTABLE;
SELECT AMOUNT AS ROLL_NO FROM MYTABLE;
SELECT * FROM MYTABLE WHERE NAME='TIRTH';
UPDATE MYTABLE SET EMAIL='DINESHGOHIL@YAHOO.COM' WHERE NAME="DINESH";
SELECT * FROM MYTABLE WHERE NAME = "DINESH";
SELECT * FROM MYTABLE WHERE ID = 1;
UPDATE MYTABLE SET AMOUNT=38 WHERE ID = 1;
SELECT * FROM MYTABLE;
SELECT * FROM MYTABLE WHERE NAME="DINESH";
UPDATE MYTABLE SET EMAIL='DINESHGOHIL@YAHOO.COM' WHERE NAME="DINESH";
SELECT * FROM MYTABLE WHERE NAME = "DINESH";
DELETE FROM MYTABLE WHERE NAME = 'DINESH';
DELETE FROM MYTABLE WHERE NAME = 'TIRTH';
