SHOW DATABASES;
USE SAKILA;
SELECT * FROM CITY;
SELECT * FROM COUNTRY;

#INNER JOIN
SELECT CITY.CITY_ID,CITY.COUNTRY_ID FROM CITY
INNER JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID;

#LEFT JOIN
SELECT CITY.CITY_ID,CITY.COUNTRY_ID,CITY.LAST_UPDATE,COUNTRY.LAST_UPDATE FROM CITY
LEFT JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID;

##RIGHT JOIN
SELECT CITY.CITY_ID,COUNTRY.COUNTRY_ID,CITY.LAST_UPDATE,COUNTRY.LAST_UPDATE FROM CITY
RIGHT JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID;

# FULL OUTER JOIN
SELECT * FROM CITY
LEFT JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID
UNION
SELECT * FROM CITY
RIGHT JOIN COUNTRY
ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID



