/* PROCEDURE TO FIND OUT SQURE ROOT OF ANY NUMBER*/
CREATE DATABASE N1;
USE N1;
/* SQURE _ROOT OF ANY NUMBER */

DELIMITER $$
CREATE PROCEDURE SQRT_ROOT(A INT , OUT B FLOAT)
BEGIN
SET B = SQRT(A);
END $$
DELIMITER ;

CALL SQRT_ROOT(64, @B);
SELECT @B

DELIMITER $$
CREATE PROCEDURE POWER(OUT B FLOAT)
CALL POWER(3,2, @C);
SELECT @C


/*INOUT PROCEDURE */

DELIMITER $$
CREATE PROCEDURE SETCOUNTER(INOUT COUNTER INT, IN INC INT )
BEGIN
SET COUNTER = COUNTER + INC;
END $$
SET @COUNTER = 1;
SELECT @COUNTER

DELIMITER //
CREATE PROCEDURE USER_VAR()
BEGIN
	SET @X = 15;
    SET @Y = 10;
    SELECT @X,@Y, @X-@Y;
END//

CALL USER_VAR();
